version: 2.1
orbs:
  python: circleci/python@0.3.0
  sam: circleci/aws-sam-serverless@1.0.1
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Test
          command: nosetests tests/unit/
  deploy:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run:
          name: Deploy to AWS
          command: |
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh
workflows:
  deploy_chow_backend:
    jobs:
      - build
      - deploy:
          context: CHOW_BACKEND
          requires:
            - build