version: 2.1
orbs:
  python: circleci/python@0.3.0
  aws-cli: circleci/aws-cli@1.2.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Test
          command: nosetests tests/unit/
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Install Zip
          command: brew install zip
      - run:
          name: Deploy to AWS
          command: |
            chmod +x ./scripts/deploy.sh
            ./scripts/deploy.sh
workflows:
  deploy_chow_backend:
    jobs:
      - build
      - deploy:
          requires:
            - build
